/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package aplikasi_catatan_perjalanan;

import java.awt.Dimension;
import java.awt.Image;
import java.io.File;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.SwingUtilities;


/**
 *
 * @author Gumilang
 */
public class Card extends javax.swing.JPanel {
    dbConnection db=new dbConnection();
    String path ,tgl, lks, dsk, idStr;
    menu_utama mu = (menu_utama) SwingUtilities.getWindowAncestor(this);
    /**
     * Creates new form Card
     */
    public Card(String tanggal, String lokasi, String deskripsi, String foto_lokasi, int id) {
        initComponents();
        lbl_tanggal.setText(tanggal);
        tgl=tanggal;
        lbl_lokasi.setText(lokasi);
        lks=lokasi;
        lbl_deskripsi.setText(deskripsi);
        dsk=deskripsi;
        path=foto_lokasi;
        ImageIcon icon = new ImageIcon(new ImageIcon(foto_lokasi).getImage());
        Image scaledImage = icon.getImage().getScaledInstance(153, 153, Image.SCALE_DEFAULT);
        icon = new ImageIcon(scaledImage);
        lbl_foto.setIcon(icon);
        idStr = Integer.toString(id); 
        lbl_id.setText(idStr);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbl_lokasi = new javax.swing.JLabel();
        lbl_tanggal = new javax.swing.JLabel();
        lbl_foto = new javax.swing.JLabel();
        btn_hapus = new javax.swing.JButton();
        btn_ubah = new javax.swing.JButton();
        lbl_id = new javax.swing.JLabel();
        lbl_deskripsi = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setMaximumSize(new java.awt.Dimension(713, 566));

        lbl_lokasi.setText("Nama");

        lbl_tanggal.setText("jLabel3");

        lbl_foto.setText("jLabel2");
        lbl_foto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        btn_ubah.setText("Ubah");
        btn_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ubahActionPerformed(evt);
            }
        });

        lbl_id.setText("jLabel2");

        lbl_deskripsi.setText("jLabel2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_foto, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_lokasi)
                            .addComponent(lbl_tanggal)
                            .addComponent(lbl_id)
                            .addComponent(lbl_deskripsi))
                        .addContainerGap(253, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_ubah)
                        .addGap(9, 9, 9)
                        .addComponent(btn_hapus)
                        .addGap(10, 10, 10))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_id)
                        .addGap(10, 10, 10)
                        .addComponent(lbl_lokasi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_tanggal)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_foto, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_deskripsi))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_ubah)
                            .addComponent(btn_hapus))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ubahActionPerformed
        menu_utama mu = (menu_utama) SwingUtilities.getWindowAncestor(this);
        mu.setUpdate(this.tgl, this.lks, this.dsk, this.path, this.idStr);
        mu.setSelectedTab(2);
    }//GEN-LAST:event_btn_ubahActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here:
        // Dapatkan objek menu_utama
        
        try {
            String id = lbl_id.getText();
            PreparedStatement stat = db.getCon().prepareStatement("DELETE FROM catatan WHERE id_catatan=?");
            stat.setString(1, id);
            int rowsDeleted = stat.executeUpdate();
            
            if (rowsDeleted > 0) {
                 // Hapus file gambar
                if (!path.isEmpty()) {
                    File file = new File(path);
                    if (file.delete()) {
                        System.out.println("File " + path + " berhasil dihapus");
                    } else {
                        System.out.println("File " + path + " gagal dihapus");
                    }
                }
                JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
                // Panggil method setPanel
                menu_utama mu = (menu_utama) SwingUtilities.getWindowAncestor(this);
                mu.setPanel("tanggal");
            } else {
                JOptionPane.showMessageDialog(null, "Data gagal dihapus");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btn_hapusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_ubah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_deskripsi;
    private javax.swing.JLabel lbl_foto;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JLabel lbl_lokasi;
    private javax.swing.JLabel lbl_tanggal;
    // End of variables declaration//GEN-END:variables
}
